name: ChestGuard
main: Napol\ChestGuard
author: NapolGamer TH
version: 1.0
api: [3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.1]
load: POSTWORLD
description: Guards your chest 
website: https://github.com/NapolGamerTH/ChestGuard/
commands:
 cg:
  desciption: Lock and unlock chests
  usage: /cg <option>
  permission: chestguard.command.cg
 scg:
  desciption: PocketGuard command for op user
  usage: /scg <option>
  permission: chestguard.command.scg
permissions:
 chestguard:
  default: op
  description: "Allows using all the ChestGuard things"
  children:
   chestguard.command:
    default: op
    description: "Allows using all the ChestGuard commands"
    children:
     chestguard.command.cg:
      default: true
      description: "Allows using /cg command"
     chestguard.command.scg:
      default: op
      description: "Allows using /scg command"
   chestguard.op:
    default: op
    description: "Allows breaking all locked chests"
